version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm:start --prefix combined/server
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      VITE_DISCORD_CLIENT_ID: ${VITE_DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
    volumes:
      - ./src:/usr/src/app/combined

# You can define a .env file in the same directory as this docker-compose.yml
# to provide the required environment variables.
